#!/system/bin/sh

echo "hello"

apt update -y

apt upgrade -y

apt install curl -y

apt-get install gnupg -y

curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

echo "install completed"
